/**
 * Post-agent hook for evyasys-train-docs.
 *
 * Parses structured agent output (<!-- EVYADOC: filename --> delimiters),
 * writes each document to .evyasys/docs/, and generates an INDEX.md navigation hub.
 *
 * Expected agent output format:
 *   <!-- EVYADOC: ARCHITECTURE.md -->
 *   [document content]
 *   <!-- EVYADOC: STACK.md -->
 *   [document content]
 *   ...
 */
const path = require('path');
const fs   = require('fs');
const { loadConfig } = require('../../scripts/lib/config');
const contextDoc     = require('../../scripts/lib/context-doc');

/**
 * Split agent output on <!-- EVYADOC: filename --> delimiters.
 * Returns a map of filename → content.
 * @param {string} output
 * @returns {Record<string, string>}
 */
function parseDocs(output) {
  const docs     = {};
  const segments = output.split(/<!--\s*EVYADOC:\s*/);
  for (const segment of segments.slice(1)) {
    const delimEnd = segment.indexOf('-->');
    if (delimEnd === -1) continue;
    const name    = segment.slice(0, delimEnd).trim();
    const content = segment.slice(delimEnd + 3).trim();
    if (name && content) docs[name] = content;
  }
  return docs;
}

/**
 * Build the INDEX.md navigation hub.
 * Generated by the hook — not by the agent — so it always reflects what was written.
 * @param {string[]} written - sorted list of written filenames
 * @param {string} date - ISO date string YYYY-MM-DD
 * @returns {string}
 */
function buildIndex(written, date) {
  const sorted = [...written].sort();
  return [
    '# Project Documentation Index',
    '',
    `> Generated by /evyasys:TrainDocs on ${date}`,
    `> Re-run \`/evyasys:TrainDocs --update\` to regenerate after major codebase changes.`,
    '',
    '## Code quality gate',
    '',
    'Every document in this folder is a **code quality gate** for this project.',
    'All new development must follow the standards defined here.',
    '',
    'The `/evyasys:StartDev` workflow loads `ARCHITECTURE.md`, `RULES.md`,',
    '`STANDARDS.md`, and `PATTERNS.md` at Step 0 before generating any technical plan.',
    '',
    '## Documents',
    '',
    ...sorted.map(name => `- [${name}](./${name})`),
    '',
    '---',
    '',
    '*Maintained by EvyaGovernance — re-run `/evyasys:TrainDocs --update` after major stack or architecture changes.*',
  ].join('\n');
}

module.exports = async function (ctx) {
  const cfg = await loadConfig({ ctx });

  // ── Guard ─────────────────────────────────────────────────────────────────────
  const output = ctx.agentResult;
  if (!output) {
    ctx.send('No documentation output from agent — aborting.');
    return;
  }

  // ── Parse ─────────────────────────────────────────────────────────────────────
  const docs     = parseDocs(output);
  const docNames = Object.keys(docs);

  if (docNames.length === 0) {
    ctx.send(
      'Could not parse any documents from agent output. ' +
      'Ensure the agent used <!-- EVYADOC: FILENAME.md --> delimiters.',
    );
    return;
  }

  ctx.send(`Parsed ${docNames.length} document(s): ${docNames.join(', ')}`);

  // ── Confirm before writing ─────────────────────────────────────────────────────
  if (!(await ctx.confirm(`Write ${docNames.length} documents to .evyasys/docs/ in ${cfg.repoRoot}?`))) {
    ctx.send('Cancelled — no files written.');
    return;
  }

  // ── Write to disk ─────────────────────────────────────────────────────────────
  const docsDir = path.join(cfg.repoRoot, '.evyasys', 'docs');
  fs.mkdirSync(docsDir, { recursive: true });

  const created = [];
  const updated = [];

  for (const [name, content] of Object.entries(docs)) {
    const docPath = path.join(docsDir, name);
    fs.mkdirSync(path.dirname(docPath), { recursive: true });
    const isNew = !fs.existsSync(docPath);
    fs.writeFileSync(docPath, content + '\n', 'utf8');
    (isNew ? created : updated).push(name);
  }

  const written = [...created, ...updated];

  // ── INDEX.md — always regenerated, never user-edited ──────────────────────────
  const today = new Date().toISOString().split('T')[0];
  fs.writeFileSync(
    path.join(docsDir, 'INDEX.md'),
    buildIndex(written, today) + '\n',
    'utf8',
  );

  // ── Refresh the always-loaded project summary ─────────────────────────────────
  const ctxRes = contextDoc.regenerate(cfg.repoRoot);

  // ── Success ───────────────────────────────────────────────────────────────────
  if (created.length) ctx.send(`✅ Created (${created.length}): ${created.join(', ')}`);
  if (updated.length) ctx.send(`✅ Updated (${updated.length}): ${updated.join(', ')}`);
  ctx.send(`INDEX.md regenerated → .evyasys/docs/`);
  if (ctxRes.ok) ctx.send(`📝 .evyasys/CONTEXT.md refreshed (${ctxRes.bytes} bytes) — always-loaded project summary.`);
  ctx.send('Quality gates active. These documents are loaded by every command at Phase 0.');
};
