/**
 * Post-agent hook for evyasys-create-functional-docs.
 *
 * Parses structured agent output using <!-- EVYAFUNCDOC: filename --> delimiters,
 * writes each module document to .evyasys/docs/functional/, and builds INDEX.md.
 *
 * Agent output format:
 *   <!-- EVYAFUNCDOC: UserManagement.md -->
 *   [document content]
 *   <!-- EVYAFUNCDOC: Billing.md -->
 *   [document content]
 *   <!-- EVYAFUNCDOCINDEX
 *   [{ "name": "UserManagement", "file": "UserManagement.md", "summary": "..." }]
 *   -->
 */
const path = require('path');
const fs   = require('fs');
const { loadConfig } = require('../../scripts/lib/config');
const contextDoc     = require('../../scripts/lib/context-doc');

/**
 * Parse <!-- EVYAFUNCDOC: filename --> delimiters from agent output.
 * @param {string} output
 * @returns {Record<string, string>}
 */
function parseDocs(output) {
  const docs     = {};
  const segments = output.split(/<!--\s*EVYAFUNCDOC:\s*/);
  for (const segment of segments.slice(1)) {
    const delimEnd = segment.indexOf('-->');
    if (delimEnd === -1) continue;
    const name    = segment.slice(0, delimEnd).trim();
    const content = segment.slice(delimEnd + 3).trim();
    if (name && content) docs[name] = content;
  }
  return docs;
}

/**
 * Parse the index manifest from <!-- EVYAFUNCDOCINDEX ... --> block.
 * @param {string} output
 * @returns {Array<{name: string, file: string, summary: string}>}
 */
function parseIndex(output) {
  const match = output.match(/<!--\s*EVYAFUNCDOCINDEX\s*([\s\S]*?)-->/);
  if (!match) return [];
  try {
    return JSON.parse(match[1].trim());
  } catch {
    return [];
  }
}

/**
 * Build INDEX.md for the functional docs directory.
 * @param {Array<{name: string, file: string, summary: string}>} entries
 * @param {string[]} written - all written file names (fallback if manifest missing)
 * @param {string} date
 * @returns {string}
 */
function buildIndex(entries, written, date) {
  const rows = entries.length > 0
    ? entries.map(e => `| [${e.name}](./${e.file}) | ${e.summary} |`)
    : written.sort().map(f => `| [${f}](./${f}) | — |`);

  return [
    '# Functional Documentation Index',
    '',
    `> Generated by /evyasys:CreateFunctionalDocs on ${date}`,
    `> Re-run \`/evyasys:CreateFunctionalDocs --update <ModuleName>\` after significant business logic changes.`,
    '',
    '## Purpose',
    '',
    'These documents describe **what** each module does — in plain language, for non-technical readers.',
    'They are structured for RAG retrieval: each section answers a specific category of question.',
    '',
    '## Modules',
    '',
    '| Module | Description |',
    '|---|---|',
    ...rows,
    '',
    '---',
    '',
    '*Maintained by EvyaGovernance — re-run `/evyasys:CreateFunctionalDocs --update <ModuleName>` after significant feature changes.*',
  ].join('\n');
}

module.exports = async function (ctx) {
  const cfg = await loadConfig({ ctx });

  const output = ctx.agentResult;
  if (!output) {
    ctx.send('No functional documentation output from agent — aborting.');
    return;
  }

  const docs    = parseDocs(output);
  const docNames = Object.keys(docs);

  if (docNames.length === 0) {
    ctx.send(
      'Could not parse any functional documents from agent output. ' +
      'Ensure the agent used <!-- EVYAFUNCDOC: ModuleName.md --> delimiters.',
    );
    return;
  }

  ctx.send(`Parsed ${docNames.length} functional document(s): ${docNames.join(', ')}`);

  if (!(await ctx.confirm(`Write ${docNames.length} functional doc(s) to .evyasys/docs/functional/ in ${cfg.repoRoot}?`))) {
    ctx.send('Cancelled — no files written.');
    return;
  }

  const functionalDir = path.join(cfg.repoRoot, '.evyasys', 'docs', 'functional');
  fs.mkdirSync(functionalDir, { recursive: true });

  const created = [];
  const updated = [];

  for (const [name, content] of Object.entries(docs)) {
    const docPath = path.join(functionalDir, name);
    const isNew   = !fs.existsSync(docPath);
    fs.writeFileSync(docPath, content + '\n', 'utf8');
    (isNew ? created : updated).push(name);
  }

  const written = [...created, ...updated];
  const entries = parseIndex(output);
  const today   = new Date().toISOString().split('T')[0];

  fs.writeFileSync(
    path.join(functionalDir, 'INDEX.md'),
    buildIndex(entries, written, today) + '\n',
    'utf8',
  );

  if (created.length) ctx.send(`✅ Created (${created.length}): ${created.join(', ')}`);
  if (updated.length) ctx.send(`✅ Updated (${updated.length}): ${updated.join(', ')}`);
  ctx.send(`INDEX.md regenerated → .evyasys/docs/functional/`);

  const ctxRes = contextDoc.regenerate(cfg.repoRoot);
  if (ctxRes.ok) ctx.send(`📝 .evyasys/CONTEXT.md refreshed (${ctxRes.bytes} bytes).`);

  ctx.send('Functional docs ready. Use /evyasys:CreateFunctionalDocs --update <ModuleName> after significant feature changes.');
};
